name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
          # ┌───────────── minute (0–59)
          # │ ┌───────────── hour (0–23)
          # │ │ ┌───────────── day of the month (1–31)
          # │ │ │ ┌───────────── month (1–12)
          # │ │ │ │ ┌───────────── day of the week (0–6) (Sunday to Saturday;
          # │ │ │ │ │                                   7 is also Sunday on some systems)
          # │ │ │ │ │
          # │ │ │ │ │
          # * * * * * <command to execute>
   - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Refresh blog posts list
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.tricky.cat/feed.xml"
          retry_count: 3
          retry_wait_time: 5
